# Generated by Django 2.1.7 on 2019-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.DateTimeField(),
        ),
    ]
